### ISSUE TITLE
Eliminate unnecessary code when args/ret aren't supplied

### ISSUE THREAD

**Issue by usernolan** [Nolan330/fm#3]

**Comment by localshred** [comment]
When pushing a `defm` through the `fm.test.check/check` function, we end up getting a failure since the default args spec provided (in the case below, `(s/tuple any?)`) will generate input data conforming to the `any?` predicate (read: any kind of data).

```clojure
(ns user
  (:require [clojure.alpha.spec.test :as stest]
                 [fm.macros :refer [defm]]
                 [fm.test.check :as fm.check]))

(defm test1 [n] (inc n))
(fm.check/fmdef! (meta test1))
(stest/check 'user/test1) ;; => lots and lots of anomalies
```

For me this means if an `:fm/args` spec isn't provided, at least for the purposes of `check`, we shouldn't attempt to test this function against `fm` anomaly handling. This could mean we no-op and default back to a `defn`, or we provide something in the meta map that would indicate it. The second option is less than ideal, as I'm guessing we should try to keep the meta map as small and simple as possible.

I'm unclear if only a `:fm/ret` is provided without an `:fm/args` if the `check` function should be run on it. It would seem to incur the same problem.

However if a `:fm/handler` is provided, we shouldn't no-op on wrapping the body in a `try` form.

After thinking through this a little bit it seems like we shouldn't inject a default args or ret spec verification if one isn't provided. Perhaps a `::no-op` spec that I can check against when deciding if we should translate to `s/fdef`. Thoughts?

**Comment by usernolan** [comment]
#11
