### ISSUE TITLE
Convert positional args predicates/specs to s/cat catenations

### ISSUE THREAD

**Issue by localshred** [Nolan330/fm#7]
See #6 

We're adding automatic conversion from `defm` definitions to `s/fdef` so that we can pipe straight through to `stest/check`. Unfortunately fdef doesn't work with the style that fm allows providing a set of predicates in the same shape as the args list for a fn, so `fm-form` needs to rewrite the provided `:fm/args` argument list into an `(s/cat ...)` expression with the arg names tagged appropriately.

```clojure
;; fm-form should turn this...
(defm test
  ^{:fm/args [int? [int? int?]]}
  [x [y z]]
  (+ x y z))

;; into this...
(defm test
  ^{:fm/args (s/cat :x int? (s/cat :y int? :z int?))}
  [x [y z]]
  (+ x y z))
```

We may also want to consider providing `gen/gen-from-pred` where available on incoming predicates.

**Comment by usernolan** [comment]
Spot on. Pedantically, we'll need a tag for the nested `s/cat`s, e.g.

```
(defm test
  ^{:fm/args (s/cat :x int? ?TAG (s/cat :y int? :z int?))}
  [x [y z]]
  (+ x y z))
```

It will probably look something like

```
(keyword nested#) ; ?TAG
```

i.e. some prefixed `auto-gensym`, since there isn't a very organic name to apply, and to avoid collisions.

This will also have enormously positive implications on anomaly handling, specifically w.r.t. `:fm.utils/args-anomaly` and `:fm.utils/received-anomaly`. We won't know exactly what this will look like until we've gotten a bit further with implementing `s/cat`, but it should be pretty clean.

**Comment by usernolan** [comment]
https://github.com/Nolan330/fm/pull/8 for where this landed.

**Comment by usernolan** [comment]
https://github.com/Nolan330/fm/pull/8
